sudo: true
os:
    - linux
    - osx
    - windows
language: node_js
node_js:
    - 8
    - 9
    - 10
    - 11
cache:
    directories:
        - node_modules
        - "$HOME/.npm"

service:
    - redis-server

before_script:
    - sudo redis-server /etc/redis/redis.conf --port 6379 --requirepass 'LahmYyc'

script:
    - npm run lint
    - npm run test-cov

after_script:
    - npm install codecov
    - ./node_modules/.bin/codecov
