language: node_js
node_js:
    - 8
    - 9
    - 10
    - 11
cache:
    directories:
        - node_modules
        - "$HOME/.npm"

service:
    - redis-server

script:
    - npm run lint
    - npm run test-cov

before_scripe:
    - sudo redis-server /etc/redis/redis.conf --port 6379

after_script:
    - npm install codecov
    - ./node_modules/.bin/codecov
